name: maid MacOS Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Build for x86_64
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build for aarch64
        run: cargo build --release --target aarch64-apple-darwin

      - name: Combine into universal binary
        run: |
          mkdir -p dist/MaidCode
          lipo -create \
            target/x86_64-apple-darwin/release/maid \
            target/aarch64-apple-darwin/release/maid \
            -output dist/MaidCode/maid
          chmod +x dist/MaidCode/maid

      - name: Copy repo folders
        run: |
          cp -r library dist/MaidCode/
          cp -r LICENSE dist/MaidCode/
          cp -r README.md dist/MaidCode/

      - name: Create zip file
        run: |
          cd dist
          zip -r MaidCode_+macos.zip MaidCode

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: MaidCode_+macos
          path: dist/MaidCode_+macos.zip
